apiVersion: v1
kind: Service
metadata:
  name: javeriana-service
spec:
  selector:
    app: javeriana-app
  ports:
    - protocol: TCP
      port: 8081  # Puerto externo
      targetPort: 8081  # Puerto en el contenedor
  type: LoadBalancer  # Usa NodePort si estás en Minikube

